### ISSUE TITLE
compile error: pg-io.d.ts is not a module

### ISSUE THREAD

**Issue by m12i** [herculesinc/pg-dao#3]
Hi, 
I have done:
`npm install —save pg-dao`

it does get installed in node_modules, but then I get compile error as:

`node_modules/pg-dao/pg-dao.d.ts(5,25): error TS2656: Exported external package typings file '/Users/myuser/git/transit-pairs/node_modules/pg-io/pg-io.d.ts' is not a module. Please contact the package author to update the package definition.`

Any idea what has gone wrong?
Thank you,
Mahmood

**Comment by irakliy81** [comment]
It was working fine for me - but maybe it depends on the build system that you are using.

I've flattened out the type definition file. Thinking it should help. Try using version 0.7.2 - and let me know if you still getting the same error.
